import { EditableProvider } from '@/components/organism/Editable';
import '@/styles/global.css';
import { NextAuthProvider } from '@/components/providers/next-auth';

export const metadata = {
  title: "Women's Board",
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Mulish:wght@500&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <NextAuthProvider>
          <EditableProvider>{children}</EditableProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
